Для успішного виконання домашки використовуйте документацію [NumPy](https://numpy.org/doc/stable/).

Зверніть увагу на такі методи `numpy`:
* *arange*
* *zeros*
* *ones*
* *full*
* *nonzero*
* *eye*
* *random*
* *sort*
* *sum*
* *min*
* *mean*

In [2]:
import numpy as np

In [23]:
# Завдання 1: Створити масив розміром 3x3 зі значеннями від 0 до 8
# Hints: np.arange
arr1 = np.arange(9).reshape(3, 3)
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [24]:
# Завдання 2: Створити вектор розміром 10, заповнений нулями
arr2 = np.zeros(10)
print(arr2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
# Завдання 3: Створити вектор розміром 10, заповнений одиницями
arr3 = np.ones(10)
print(arr3)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [26]:
# Завдання 4: Створити вектор розміром 10, заповнений значеннями 5
# Hints: np.full
arr4 = np.full(10, 5)
print(arr4)

[5 5 5 5 5 5 5 5 5 5]


In [27]:
# Завдання 5: Створити вектор з числами від 10 до 49
arr5 = np.arange(10, 50)
print(arr5)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [28]:
# Завдання 6: Реверсувати порядок елементів вектора з завдання 5
arr6 = arr5[::-1]
print(arr6)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [29]:
# Завдання 7: Створити 9x9 матрицю зі значеннями від 0 до 80
# Hints: np.arange
arr7 = np.arange(81).reshape(9, 9)
print(arr7)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]


In [30]:
# Завдання 8: Знайти індекси ненульових елементів вектора [1,2,0,0,4,0]
# Hints: np.nonzero
arr8 = np.nonzero(np.array([1,2,0,0,4,0]))
print(arr8)

(array([0, 1, 4]),)


In [22]:
# Завдання 9: Створити одиничну матрицю розміром 3x3
# Hints: np.eye
arr9 = np.eye(3)
print(arr9)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
# Завдання 10: Створити випадковий вектор розміром 10 та відсортувати його
arr10 = np.random.rand(10)
arr10_sorted = np.sort(arr10)
print(arr10)
print(arr10_sorted)

[0.65385682 0.97632661 0.0670329  0.52967754 0.62416723 0.17297858
 0.84616187 0.23222941 0.03785764 0.09913437]
[0.03785764 0.0670329  0.09913437 0.17297858 0.23222941 0.52967754
 0.62416723 0.65385682 0.84616187 0.97632661]


In [38]:
# Завдання 11: Створити матрицю 5x5 з випадковими цілими числами в діапазоні від 0 до 10
arr11 = np.random.randint(11, size=(5, 5))
print(arr11)

[[10  0  8  7  3]
 [ 0  3  0  9  3]
 [ 5  7  1  0  2]
 [ 7  0  1  4  4]
 [ 9  8  1  2  7]]


In [39]:
# Завдання 12: Обчислити суму всіх елементів матриці з завдання 11
arr11_sum = np.sum(arr11)
print(arr11_sum)

101


In [40]:
# Завдання 13: Знайти найменше значення в кожному рядку матриці з завдання 11
arr11_min_row = np.min(arr11, axis=1)
print(arr11_min_row)

[0 0 0 0 1]


In [41]:
# Завдання 14: Обчислити середнє значення кожного стовпця матриці з завдання 11
arr11_mean_col = np.mean(arr11, axis=0)
print(arr11_mean_col)

[6.2 3.6 2.2 4.4 3.8]


In [42]:
# Завдання 15: Створити випадковий вектор розміром 15 та замінити максимальне значення на -1
# Hints: np.argmax
arr15 = np.random.randint(1, 100, size=15)
print(arr15)
arr15[np.argmax(arr15)] = -1
print(arr15)

[43 28  3 81 16 19 64 23 51  5 64 56 64 13 62]
[43 28  3 -1 16 19 64 23 51  5 64 56 64 13 62]


In [43]:
# Завдання 16: Перетворити випадковий вектор розміром 10 в матрицю розміром 2x5
arr16 = np.random.randint(1, 100, size=10)
print(arr16)
arr16 = arr16.reshape(2, 5)
print(arr16)

[71 64 26 66  3 17  5  9 45 38]
[[71 64 26 66  3]
 [17  5  9 45 38]]


In [44]:
# Завдання 17: Знайти середнє значення елементів матриці з завдання 16
arr16_mean = np.mean(arr16)